
task main() {
	int leftMotor, rightMotor;
	bool isOnAutomatedPart;
	//-----------------------code for controller------------
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, encoder);
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, encoder);
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder);
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder);
#pragma config(Sensor, port5,  colorDetector,  sensorVexIQ_Color12Color);
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	/*------------------------------------------------------------------------------------------------
	This program will use the VEX IQ Wirless Controller to drive your Clawbot. This program will use
	"Tank Mode" to enable two joysticks to drive the two main motors of the Clawbot.

	The 4 joystick axis on the VEX IQ Wireless Controller return values from -127 to +127.

	Note: You will have to set ROBOTC to enable "Wireless Control" to use the VEX IQ joystick.

	ROBOT CONFIGURATION: VEX IQ Clawbot
	MOTORS & SENSORS:
	[I/O Port]          [Name]              [Type]                			[Location]
	Port 1        			leftMotor           VEX IQ Motor (Reversed)		  Left side motor
	Port 6       				rightMotor          VEX IQ Motor 							  Right side motor
	Port 10							armMotor						VEX IQ Motor								Arm Up/Down motor
	Port 11							clawMotor						VEX IQ Motor								Claw Open/Close motor
	------------------------------------------------------------------------------------------------*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*------------------------------------------------------------------------------------------------
	This program will show the VEX IQ Color sensor in "12 Color" mode. This mode will return a specific
	color values as opposed to a "Hue" value. This is helpful for detecting specific colors.

	The 12 valid color names are:
	colorRedViolet / colorRed / colorDarkOrange / colorOrange /	colorDarkYellow /	colorYellow /
	colorLimeGreen / colorGreen /	colorBlueGreen / colorBlue / colorDarkBlue /  colorViolet

	The "getColorValue" command will return one of the 12 named colors, so a simple "equal to"
	works the best. This program uses 12 if/else blocks to do the comparison.

	ROBOT CONFIGURATION: VEX IQ Clawbot
	MOTORS & SENSORS:
	[I/O Port]          [Name]              [Type]                			[Location]
	Port 5       				colorDetector       VEX IQ Color		      			Color Detector (12 Color Mode)
------------------------------------------------------------------------------------------------*/

	repeat(forever){
	sleep(25); //might help program
	if (isOnAutomatedPart == false)
	{
	 setMotorSpeed(leftMotor, getJoystickValue(ChA));
	 setMotorSpeed(rightMotor, getJoystickValue(ChD));
	}
	if(getColorName(colorDetector) == colorRed)  					 //Color #2
		{
		 isOnAutomatedPart = true;
		}
	if (isOnAutomatedPart == true)
		{
		 setMotorSpeed(leftMotor, 64);     	//ramp up speed
   	 setMotorSpeed(rightMotor, 64);			//drive forward
   	 setMotorSpeed(leftMotor, 127); 		//full speed
   	 setMotorSpeed(rightMotor, 127); 		//drive forward
   	 sleep(1000);     // Wait for 1 seconds
   	 setMotorSpeed(leftMotor, 0);  //Stop Motors
   	 setMotorSpeed(rightMotor, 0);
   	 setMotorSpeed(leftMotor, 16); //turn right
   	 sleep(1000);  //Wait for 1 second
   	 setMotorSpeed(leftMotor, 0); //Stop turning right
   	 //setMotorSpeed(scoopMotor, 8);
   	 //sleep(1000);
   	 //setMotorSpeed(scoopMotor, 0);
   	 /*
   	 Put code for driving motor until red is detected and then
   	 move forward a bit to exit the automated range*/

   	 isOnAutomatedPart = false;
   	}
}
}
